- name: Ubuntu CI
  # hosts: "{{ host | default('all') }}"
  hosts: "localhost"

  vars:
    platform: ubuntu

    llvm2cpg_cxx_flags: -D_GLIBCXX_USE_CXX11_ABI=1

    packages:
      - vim
      - wget
      - git
      - ninja-build
      - libz-dev
      - ncurses-dev
      - libstdc++6
      - pkg-config
      - libxml2-dev
      - binutils
      - unzip
      # - sbt
      - openjdk-8-jdk
      - openjdk-8-jre
      - python3
      - python3-pip
      - python3-pkg-resources

    python_packages:
      - lit
      - filecheck==0.0.22

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include: helpers/working-dir.yaml

    - name: Install Required Packages
      apt:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Install Python packages
      pip:
        name: "{{ python_packages }}"
        state: present
        executable: pip3

    # - name: Install Python packages
    #   command: pip3 install "{{ python_packages }}"
    #   # args: 
    #     # name: "{{ python_packages }}"
    #     # state: present
    #     # executable: pip3

    - name: Download CMake
      get_url:
        url: https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.sh
        dest: "{{ working_dir }}/cmake.sh"
      register: download_cmake

    - name: Install CMake
      shell: sh {{ working_dir }}/cmake.sh --prefix=/usr/local --skip-license
      args:
        creates: /usr/local/bin/cmake
      when: download_cmake.changed
      become: true

    # - name: Install Ocular
    #   include: helpers/install-ocular.yaml

    - name: Install Sbt
      include: helpers/install-sbt.yaml

    - name: Install Joern
      include: helpers/install-joern.yaml

    - name: Install LLVM
      include: helpers/install-llvm.yaml

    - name: Install Protobuf
      include: helpers/install-protobuf.yaml

    - name: Install Libzip
      include: helpers/install-libzip.yaml

    - name: Build and test
      include: helpers/build-and-test.yaml

    - name: Package
      include: helpers/package.yaml
